.PHONY: clean All

All:
	@echo "----------Building project:[ StackWithVector - Debug ]----------"
	@"$(MAKE)" -f  "StackWithVector.mk"
clean:
	@echo "----------Cleaning project:[ StackWithVector - Debug ]----------"
	@"$(MAKE)" -f  "StackWithVector.mk" clean
